name: AUR captcha helper

on:
  workflow_dispatch:

jobs:
  captcha:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Get captcha answer
        run: |
          LC_ALL=C pacman -V|sed -r 's#[0-9]+#80c#g'|md5sum|cut -c1-6
